version: 2.1
orbs:
  docker: circleci/docker@1.7.0
jobs:
  build:
    docker:
      - image: circleci/php:8.1-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          registry-url: https://index.docker.io/v1/
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build and Test
          command: |
            docker-compose -f docker-compose.yml up -d
            docker-compose exec php composer install
            # Add here any other command you need for testing
      - run:
          name: Deploy
          command: |
            chmod +x ./deploy.sh
            ./deploy.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
